
package examen2eduardoespionozarodriguez;

import static examen2eduardoespionozarodriguez.ClsEncuesta.apellidos;
import static examen2eduardoespionozarodriguez.ClsEncuesta.conductores;
import static examen2eduardoespionozarodriguez.ClsEncuesta.correo;
import static examen2eduardoespionozarodriguez.ClsEncuesta.edad;
import static examen2eduardoespionozarodriguez.ClsEncuesta.nconductores;
import static examen2eduardoespionozarodriguez.ClsEncuesta.nencuesta;
import static examen2eduardoespionozarodriguez.ClsEncuesta.nombre;
import javax.swing.JOptionPane;

/**
 *
 * @author Edu
 */
public class IntEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form IntEncuesta
     */
    public IntEncuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tnombre = new javax.swing.JTextField();
        LNE = new javax.swing.JLabel();
        LA = new javax.swing.JLabel();
        LNC = new javax.swing.JLabel();
        LE = new javax.swing.JLabel();
        LCE = new javax.swing.JLabel();
        tapellido = new javax.swing.JTextField();
        tedad = new javax.swing.JTextField();
        tcorreo = new javax.swing.JTextField();
        LDC = new javax.swing.JLabel();
        bsi = new javax.swing.JRadioButton();
        bno = new javax.swing.JRadioButton();
        numenc = new javax.swing.JLabel();
        bregistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnombreActionPerformed(evt);
            }
        });

        LNE.setText("#Encuesta");

        LA.setText("Apellidos");

        LNC.setText("Nombre completo");

        LE.setText("Edad");

        LCE.setText("Correo Electronico");

        LDC.setText("¿Dispone de un carro?");

        buttonGroup1.add(bsi);
        bsi.setText("Si");
        bsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsiActionPerformed(evt);
            }
        });

        buttonGroup1.add(bno);
        bno.setText("No");
        bno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoActionPerformed(evt);
            }
        });

        numenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bregistrar.setText("Registrar");
        bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregistrarActionPerformed(evt);
            }
        });

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LCE)
                            .addComponent(LE)
                            .addComponent(LA)
                            .addComponent(LDC)
                            .addComponent(LNE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tnombre)
                            .addComponent(tapellido)
                            .addComponent(tedad)
                            .addComponent(tcorreo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(bno))
                            .addComponent(numenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(bregistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(523, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(LNC)
                    .addContainerGap(683, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LNE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LA)
                    .addComponent(tapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LE)
                    .addComponent(tedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCE)
                    .addComponent(tcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDC)
                    .addComponent(bsi)
                    .addComponent(bno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bregistrar)
                    .addComponent(jButton1))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(LNC)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnombreActionPerformed

    private void bregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregistrarActionPerformed
if(nombre==null)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios");
if(apellidos==null)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios"); 
if(correo==null)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios"); 
if(edad==0)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios"); 
if((edad<18)||(edad>50))JOptionPane.showMessageDialog(null, "La edad no aplica para la encuesta");
    }//GEN-LAST:event_bregistrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
nencuesta++;     
numenc.setText(String.valueOf(nencuesta));
    }//GEN-LAST:event_formWindowActivated

    private void bsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiActionPerformed
conductores++;        // TODO add your handling code here:
    }//GEN-LAST:event_bsiActionPerformed

    private void bnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoActionPerformed
nconductores++;        // TODO add your handling code here:
    }//GEN-LAST:event_bnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(nombre==null)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios");
if(apellidos==null)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios"); 
if(correo==null)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios"); 
if(edad==0)JOptionPane.showMessageDialog(null, "Por favor,llena los espacios"); 
if((edad<18)||(edad>50))JOptionPane.showMessageDialog(null, "La edad no aplica para la encuesta");
else new ImprimirResultados().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
//LCPO.setText(String.valueOf(cantidadPollo));
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LA;
    private javax.swing.JLabel LCE;
    private javax.swing.JLabel LDC;
    private javax.swing.JLabel LE;
    private javax.swing.JLabel LNC;
    private javax.swing.JLabel LNE;
    private javax.swing.JRadioButton bno;
    private javax.swing.JButton bregistrar;
    private javax.swing.JRadioButton bsi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel numenc;
    private javax.swing.JTextField tapellido;
    private javax.swing.JTextField tcorreo;
    private javax.swing.JTextField tedad;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
